config/routes.rb
Rails.application.routes.draw do
  # resources :bookmarks
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'xmls#index'

  devise_for :users

  resources :users do
    resources :xmls
  end

  resources :xmls do
    collection do
      get :autocomplete
    end
  end

  resources :xmls do
    resources :bookmarks
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :xmls
  # has_many :bookmarks
  act_as_bookmarker
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/xml.rb
class Xml < ApplicationRecord
  # require 'nokogiri'
  act_as_bookmarkee
  searchkick word_start: [:name, :citation, :year, :nominal_app, :nominal_res, :headnote, :judgement,
    :case_no,:justices,:case_number,:party_details,:petitioner_advocates,:respondent_advocates,:judgement_date,
    :judgement_object_id]
    belongs_to :user

    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    index_name Rails.application.class.parent_name.underscore
    document_type self.name.downcase

    def search_data
      {
        name: name,
        citation: citation,
        year: year,
        nominal_app: nominal_app,
        nominal_res: nominal_res,
        headnote: headnote,
        judgement: judgement,
        case_no: case_no,
        justices: justices,
        case_number: case_number,
        party_details: party_details,
        petitioner_advocates: petitioner_advocates,
        respondent_advocates: respondent_advocates,
        judgement_date: judgement_date,
        judgement_object_id: judgement_object_id
      }
    end
    # def self.import(file)
    #   doc = Nokogiri::XML.parse(file)
    #   #your processing code goes here
    # end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# class BookmarksController < InheritedResources::Base
#   before_action :authenticate_user!
#   def index
#     # @xml = Xml.last
#     @bookmarks = current_user.is_bookmarker?
#   end
#
#   def new
#     @bookmark = current_user.bookmarks.build
#   end
#   #
#   # def create
#   #   @bookmark =current_user.bookmarks.build(bookmark_params)
#   #   respond_to do |format|
#   #     if @bookmark.save
#   #       format.html { redirect_to @bookmark, notice: 'successfully created.' }
#   #       format.json { render :show, status: :created, location: @bookmark }
#   #     else
#   #       format.html { render :new }
#   #       format.json { render json: @bookmark.errors, status: :unprocessable_entity }
#   #     end
#   #   end
#   # end
#
#   def show
#
#   end
#
#   private
#
#   def bookmark_params
#     params.require(:bookmark).permit(:title, :url, :desciption, :favorite)
#   end
#
# end

app/controllers/xmls_controller.rb
class XmlsController < ApplicationController
  # before any blog action happens, it will authenticate the user
  before_action :authenticate_user!

  def index
    # binding.pry
    # binding.pry
    @user = current_user.email
    search = params[:term].present?
    @xml = if search
      Xml.search(search)
    else
      Xml.all
    end
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "xml.pdf",   # Excluding ".pdf" extension.
        template: "xmls/index.html.erb"
      end
    end
  end


  def show

  end

  def autocomplete
    render json: Xml.search(params[:query],{
      fields: ["name", "citation", "year","nominal_app", "nominal_res", "headnote", "judgement", "case_no",
        "justices","case_number","party_details","petitioner_advocates","respondent_advocates","judgement_date",
        "judgement_object_id"],
        match: :word_start,
        limit: 10,
        load: false,
        misspellings: {below: 5}
        }).map(&:name)
      end


      def bookmark
        # @user = current_user.email
        # @xmls = Xml.last
        # binding.pry
        User. is_bookmarker?
      end


      # def searchcriteria
      #   render json: Xml.search(params[:query], {
      #     fields: ["name", "citation", "year","nominal_app", "nominal_res", "headnote", "judgement", "case_no",
      #     "justices","case_number","party_details","petitioner_advocates","respondent_advocates","judgement_date",
      #   "judgement_object_id"],
      #     limit: 10,
      #     load: false,
      #     misspellings: {below: 5}
      #     }).map(&amp;:name)
      #   end

      #Other Restful methods show, new, edit, create, update, destroy

      # def import
      #   Xml.import(params[:file])
      #   redirect_to root_url, notice: "Products imported."
      # end

    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/xmls_helper.rb
module XmlsHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, local: true) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :desciption %>
    <%= form.text_area :desciption %>
  </div>

  <div class="field">
    <%= form.label :favorite %>
    <%= form.check_box :favorite %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Desciption</th>
      <th>Favorite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.bookmarkee_type %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.desciption %></td>
        <td><%= bookmark.favorite %></td>
        <td><%= link_to 'Show', bookmark %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Desciption:</strong>
  <%= @bookmark.desciption %>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @bookmark.favorite %>
</p>

<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XmlParsing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>  <div class='container'>
    <%= yield %>
  </div></body>
</html>

app/views/xmls/index.html.erb
<h1>Welcome !</h1>
<p><%= @user %></p>

<%# View <%= link_to 'Bookmarks', xml_bookmarks_path %>
<div class="container alert alert-light">
  <%# <% binding.pry %>
  <%= link_to 'Create PDF document', xmls_path(@xml, :format => :pdf) %>
  <%= form_tag(xmls_path, method: :get, class: "form-inline", role: 'search') do %>
  <div class="input-group">
    <%= text_field_tag :term, params[:term], placeholder: 'Search', class: 'form-control', id: 'search', autocomplete: :off %>
    <div class="input-group-btn search-panel">
      <%= submit_tag 'Search', name: nil, class: "btn btn-default", id:"search" %>
    </div>
  </div>
  <% end %>
<br><br><br>
  <% @xml.each do |x| %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Data</th>
        <input type="button" onclick="<% controller.bookmark %>">

        <%# <%= submit_tag 'Bookmark', name: nil, class: "btn btn-default" , id: "bookmark", onclick =" <%= controller.bookmark %>" %><br><br> %>
      </tr>
    </thead>
    <tbody id="myTable">
      <tr>
        <td>Name :</td>
        <td><%= x.name %></td>  </tr>
        <tr>
          <td>Citation:</td>
          <td><%= x.citation %></td>
        </tr>
        <tr>
          <td>Year:</td>
          <td><%= x.year %></td>
        </tr>
        <tr>
          <td>nominal app:</td>
          <td><%= x.nominal_app %></td>
        </tr>
        <tr>
          <td>nominal res:</td>
          <td><%= x.nominal_res %></td>
        </tr>
        <tr>
          <td>headnote:</td>
          <td><%= x.headnote %></td>
        </tr>
        <tr>
          <td>judgement:</td>
          <td><%= x.judgement %></td>
        </tr>
        <tr>
          <td>case no:</td>
          <td><%= x.case_no %></td>
        </tr>
        <tr>
          <td>justices:</td>
          <td><%= x.justices %></td>
        </tr>
        <tr>
          <td>case number:</td>
          <td><%= x.case_number %></td>
        </tr>
        <tr>
          <td>party details:</td>
          <td><%= x.party_details %></td>
        </tr>
        <tr>
          <td>petitioner advocates:</td>
          <td><%= x.petitioner_advocates %></td>
        </tr>
        <tr>
          <td>respondent advocates:</td>
          <td><%= x.respondent_advocates %></td>
        </tr>
        <tr>
          <td>judgement date:</td>
          <td><%= x.judgement_date %></td>
        </tr>
        <tr>
          <td>judgement object id:</td>
          <td><%= x.judgement_object_id %></td>
        </tr>
      </tbody>
    </table>
    <% end %>
    <script type="text/javascript">
      $(document).on('turbolinks:load',function(){
        var xmls = new Bloodhound({
          datumTokenizer: Bloodhound.tokenizers.whitespace,
          queryTokenizer: Bloodhound.tokenizers.whitespace,
          remote: {
            url: '/xmls/autocomplete?query=%QUERY',
            wildcard: '%QUERY'
          }
        });
        $("#search").typeahead(null, {
          source: xmls
        });
      })



      // $(function() {
      //  $("#bookmark").on("click", function(event) {
          // event.preventDefault();
          // $.ajax({
          //   type: "POST",
          //   url: "xmls_controller/bookmark",
          //   data: "your_form_data"
          //   success: function(data) {
          //     alert("Success");
          //   },
          // });
      //  });
      // });

    </script>